# Generated by Django 4.1.7 on 2023-03-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0003_alter_review_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_created',
            field=models.TextField(help_text='The date and time the review was created.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_edited',
            field=models.TextField(help_text='The date and time the review was last edited.', null=True),
        ),
    ]
