# Generated by Django 4.1.7 on 2023-05-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0007_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
