# Generated by Django 4.1.7 on 2023-05-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0007_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the Restaurant.', max_length=70)),
                ('description', models.TextField(help_text='Description of Restaurant')),
                ('img1', models.ImageField(upload_to='restaurant_img/')),
                ('img2', models.ImageField(upload_to='restaurant_img/')),
                ('img3', models.ImageField(upload_to='restaurant_img/')),
            ],
        ),
        migrations.RemoveField(
            model_name='bookcontributor',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookcontributor',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookContributor',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
