# Generated by Django 4.1.7 on 2023-05-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0008_restaurant_remove_bookcontributor_book_and_more'),
        ('final', '0009_reservation'),
    ]

    operations = [
    ]
