# Generated by Django 4.1.7 on 2023-05-11 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0011_restaurant_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the item', max_length=70)),
                ('price', models.IntegerField(help_text='Price of item')),
                ('img', models.ImageField(upload_to='menu_img')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final.restaurant')),
            ],
        ),
    ]
