# Generated by Django 4.2 on 2023-05-13 16:37

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0012_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_res', models.CharField(help_text='restaurant name', max_length=50)),
                ('img_res', models.ImageField(upload_to='home_img')),
                ('number_res', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address_res', models.CharField(help_text='res address', max_length=70)),
                ('about_res', models.CharField(help_text='res about', max_length=255)),
                ('avg_check', models.IntegerField(help_text='avg')),
                ('kitchen', models.CharField(help_text='cook', max_length=70)),
                ('work_time', models.CharField(max_length=70)),
                ('seats', models.IntegerField(help_text='seats')),
                ('vip_zone', models.CharField(max_length=50)),
                ('chef', models.CharField(max_length=50)),
                ('about_img', models.ImageField(upload_to='home_img')),
                ('map_res', models.CharField(max_length=255)),
            ],
        ),
    ]
