# Generated by Django 4.1.7 on 2023-05-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0015_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
