# Generated by Django 4.1.7 on 2023-05-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0016_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default="{% static 'images/profile.png' %}", upload_to='ava/')),
                ('username', models.CharField(max_length=70)),
            ],
        ),
    ]
