# Generated by Django 4.2 on 2023-05-13 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0013_home'),
        ('final', '0018_alter_photo_avatar'),
    ]

    operations = [
    ]
