# Generated by Django 4.2 on 2023-05-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0019_merge_0013_home_0018_alter_photo_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='map_res',
            field=models.CharField(max_length=1000),
        ),
    ]
