# Generated by Django 5.1.1 on 2024-12-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0023_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Payment status'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='avatar',
            field=models.ImageField(blank=True, default='ava/profile-icon-design-free-vector_1.png', upload_to='ava/'),
        ),
    ]
