# Generated by Django 4.1.7 on 2023-03-01 17:01
from django.contrib import auth
from django.db import migrations, models
from PIL import Image
from phonenumber_field.modelfields import PhoneNumberField


class Reservation(models.Model):
    Username = models.CharField(help_text="Username", max_length=40)
    Name = models.CharField(help_text="Username's name", max_length=40)
    Email = models.CharField(help_text="Enmail-address", max_length=50)
    Phone_num = models.CharField(help_text="Phone number", max_length=50)
    Number = models.IntegerField(help_text="Number of guests")
    Date = models.DateField(help_text="Date of reservation")
    Time = models.CharField(help_text="Time", max_length=30)
    Res_name = models.CharField(help_text="restaurant name", max_length=40)
    Message = models.TextField(max_length=200)

    def __str__(self):
        return self.Name


class Restaurant(models.Model):
    title = models.CharField(max_length=70, help_text="The title of the Restaurant.")
    description = models.TextField(help_text="Description of Restaurant")
    logo = models.ImageField(upload_to="restaurant_img/")
    img1 = models.ImageField(upload_to="restaurant_img/")
    img2 = models.ImageField(upload_to="restaurant_img/")
    img3 = models.ImageField(upload_to="restaurant_img/")


class Menu(models.Model):
    name = models.CharField(max_length=70, help_text="Name of the item")
    price = models.IntegerField(help_text="Price of item")
    restaurant_id = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    img = models.ImageField(upload_to="menu_img")

<<<<<<< HEAD
class home(models.Model):
    name_res = models.CharField(max_length=50, help_text="restaurant name")
    img_res = models.ImageField(upload_to='home_img')
    number_res = PhoneNumberField()
    address_res = models.CharField(max_length=70, help_text='res address')
    about_res = models.CharField(max_length=255, help_text='res about')
    avg_check = models.IntegerField(help_text='avg')
    kitchen = models.CharField(max_length=70, help_text='cook')
    work_time = models.CharField(max_length=70)
    seats = models.IntegerField(help_text='seats')
    vip_zone = models.CharField(max_length=50)
    chef = models.CharField(max_length=50)
    about_img = models.ImageField(upload_to='home_img')
    map_res = models.CharField(max_length=255)
    
=======
class Photo(models.Model):
    avatar = models.ImageField(upload_to="ava/",default="ava/profile-icon-design-free-vector_1.png")
    username = models.CharField(max_length=70)
>>>>>>> 2f34bbd370707c94f26a085815fd2900099f3aab
